/**
 * WF26 CIE — Post to Slack
 * Location: src/trigger/wf26-cie-post-slack.ts
 *
 * Formats and posts the intelligence brief to Slack channels.
 * Fired by the Sunday/Wednesday orchestrators via trigger() (fire-and-forget).
 */

import { schemaTask } from "@trigger.dev/sdk/v3";
import { z } from "zod";
import axios from "axios";

const postSlackInput = z.object({
  brief: z.string(),
  actionItems: z.array(z.string()),
  contentScripts: z.array(
    z.object({
      title: z.string(),
      script: z.string(),
      platform: z.string(),
    })
  ),
  scanType: z.enum(["sunday", "wednesday"]),
  stats: z.object({
    totalScanned: z.number(),
    relevant: z.number(),
    highPriority: z.number(),
  }),
});

export const wf26CiePostSlack = schemaTask({
  id: "wf26-cie-post-slack",
  schema: postSlackInput,
  retry: {
    maxAttempts: 3,
    factor: 2,
    minTimeoutInMs: 1000,
    maxTimeoutInMs: 30000,
    randomize: true,
  },
  run: async (payload) => {
    const { brief, actionItems, contentScripts, scanType, stats } = payload;
    const slackBotToken = process.env.SLACK_BOT_TOKEN!;
    const scanLabel =
      scanType === "sunday" ? "Weekly Intelligence Brief" : "Mid-Week Update";
    const today = new Date().toISOString().split("T")[0];

    // Full brief for #maps-content-briefs
    const actionList = actionItems
      .map((item, i) => `${i + 1}. ${item}`)
      .join("\n");

    const scriptSection = contentScripts
      .map(
        (s) =>
          `*${s.title}* (${s.platform})\n>${s.script.replace(/\n/g, "\n>")}`
      )
      .join("\n\n");

    const fullMessage = `:brain: *CIE ${scanLabel} — ${today}*

:bar_chart: *Scan Stats:* ${stats.totalScanned} scanned | ${stats.relevant} relevant | ${stats.highPriority} high priority

:memo: *Executive Brief*
${brief}

:white_check_mark: *Action Items*
${actionList}

:movie_camera: *Content Scripts*
${scriptSection}

---
_Generated by WF26 Content Intelligence Engine_`;

    // Post full brief to #maps-content-briefs
    await axios.post(
      'https://slack.com/api/chat.postMessage',
      {
        channel: '#maps-content-briefs',
        text: fullMessage,
      },
      {
        headers: {
          'Authorization': `Bearer ${slackBotToken}`,
          'Content-Type': 'application/json',
        },
      }
    );

    // Shorter summary for #maps-engineering
    const summaryMessage = `:brain: *CIE ${scanLabel} — ${today}*
${stats.totalScanned} sources scanned | ${stats.relevant} relevant items | ${stats.highPriority} high priority
Top actions: ${actionItems.slice(0, 3).join(" | ")}
_Full brief posted to #maps-content-briefs_`;

    await axios.post(
      'https://slack.com/api/chat.postMessage',
      {
        channel: '#maps-engineering',
        text: summaryMessage,
      },
      {
        headers: {
          'Authorization': `Bearer ${slackBotToken}`,
          'Content-Type': 'application/json',
        },
      }
    );

    return { posted: true, scanType, date: today };
  },
});
